# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_label = QtWidgets.QLabel(self.centralwidget)
        self.frame_label.setGeometry(QtCore.QRect(10, 40, 640, 480))
        self.frame_label.setMinimumSize(QtCore.QSize(640, 480))
        self.frame_label.setMaximumSize(QtCore.QSize(640, 480))
        self.frame_label.setStyleSheet("border-radius:8px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(200,200,200);")
        self.frame_label.setText("")
        self.frame_label.setObjectName("frame_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 72, 15))
        self.label.setObjectName("label")
        self.stackedWidget_Recycle = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_Recycle.setGeometry(QtCore.QRect(730, 110, 150, 150))
        self.stackedWidget_Recycle.setStyleSheet("border-image:url(./RoundProcessBar.png) 0 0 0 0 stretch stretch;")
        self.stackedWidget_Recycle.setObjectName("stackedWidget_Recycle")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_Recycle.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_Recycle.addWidget(self.page_4)
        self.stackedWidget_Kitchen = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_Kitchen.setGeometry(QtCore.QRect(880, 110, 150, 150))
        self.stackedWidget_Kitchen.setStyleSheet("border-image:url(./RoundProcessBar.png) 0 0 0 0 stretch stretch;")
        self.stackedWidget_Kitchen.setObjectName("stackedWidget_Kitchen")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_Kitchen.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget_Kitchen.addWidget(self.page_6)
        self.stackedWidget_Harmful = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_Harmful.setGeometry(QtCore.QRect(730, 260, 150, 150))
        self.stackedWidget_Harmful.setStyleSheet("border-image:url(./RoundProcessBar.png) 0 0 0 0 stretch stretch;")
        self.stackedWidget_Harmful.setObjectName("stackedWidget_Harmful")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_Harmful.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_Harmful.addWidget(self.page_8)
        self.stackedWidget_Other = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_Other.setGeometry(QtCore.QRect(880, 260, 150, 150))
        self.stackedWidget_Other.setStyleSheet("border-image:url(./RoundProcessBar.png) 0 0 0 0 stretch stretch;")
        self.stackedWidget_Other.setObjectName("stackedWidget_Other")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.stackedWidget_Other.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.stackedWidget_Other.addWidget(self.page_10)
        self.label.raise_()
        self.frame_label.raise_()
        self.stackedWidget_Recycle.raise_()
        self.stackedWidget_Kitchen.raise_()
        self.stackedWidget_Harmful.raise_()
        self.stackedWidget_Other.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_Recycle.setCurrentIndex(0)
        self.stackedWidget_Kitchen.setCurrentIndex(0)
        self.stackedWidget_Harmful.setCurrentIndex(0)
        self.stackedWidget_Other.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "图像窗口:"))
